name: Build signed AppPruner and upload signed package (pre-release)

env:
  NOTARY_APP_PASSWORD: ${{ secrets.NOTARY_PW }}

on: [workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-26

    steps:
      - name: Checkout repo
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0
        with:
          fetch-depth: 0

      - name: Install Apple Xcode certificates
        uses: apple-actions/import-codesign-certs@8f3fb608891dd2244cdab3d69cd68c0d37a7fe93 # v2.0.0
        with:
          keychain-password: ${{ github.run_id }}
          p12-file-base64: ${{ secrets.APP_CERTIFICATES_P12 }}
          p12-password: ${{ secrets.APP_CERTIFICATES_P12_PASSWORD }}

      - name: Install Apple Installer certificates
        uses: apple-actions/import-codesign-certs@8f3fb608891dd2244cdab3d69cd68c0d37a7fe93 # v2.0.0
        with:
          create-keychain: false # do not create a new keychain for this value
          keychain-password: ${{ github.run_id }}
          p12-file-base64: ${{ secrets.PKG_CERTIFICATES_P12 }}
          p12-password: ${{ secrets.PKG_CERTIFICATES_P12_PASSWORD }}

      - name: Run build package script
        run: ./build.zsh "Release" "$NOTARY_PW"

      - name: get environment variables
        id: get_env_var
        run: |
          echo "AP_VERSION=$(/bin/cat ./build/build_info.txt)" >> $GITHUB_ENV
          echo "AP_MAIN_VERSION=$(/bin/cat ./build/build_info_main.txt)" >> $GITHUB_ENV

      - name: Create Pre-release
        id: create_pre_release
        uses: softprops/action-gh-release@v2
        with:
          name: AppPruner ${{env.AP_VERSION}}
          tag_name: v${{env.AP_VERSION}}
          draft: false
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            # Notes
            This is a pre-release version of AppPruner created by GitHub Actions.
            SupportCompanion.app has been signed and notarized. The package has been signed, notarized and stapled.

            # Changelog

            # Changes
          files: ${{github.workspace}}/release/*.pkg

      - name: Upload packages
        uses: actions/upload-artifact@v4.6.0
        with:
          name: packages
          path: release/
